---
- include: common.yml
  tags:
    - server-setup
    - common

- include: fail2ban.yml
  tags:
    - server-setup
    - fail2ban

- include: ntp.yml
  tags:
    - server-setup
    - ntp

- include: sysstat.yml
  tags:
    - server-setup
    - sysstat

- include: ssh.yml
  tags:
    - server-setup
    - ssh

- include: ufw.yml
  tags:
    - server-setup
    - ufw

- name: create user
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/bash
    home: "/home/{{ user }}"
  when: "user is defined"
